// Otomatik rating oluşturma fonksiyonları

export function generateRandomRating(min: number, max: number): number {
  const rating = Math.random() * (max - min) + min;
  return Math.round(rating * 10) / 10;
}

export function generateRandomCount(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// Bölge için rating oluştur
export function generateRegionRating(region: any) {
  const ratingValue = generateRandomRating(4.5, 4.9);
  const reviewCount = generateRandomCount(15, 50);
  const reviews = generateAutoReviews(region, reviewCount);
  
  return {
    regionId: region.id,
    regionName: region.title,
    sourceCity: region.sourceCity,
    targetCity: region.targetCity,
    aggregateRating: {
      ratingValue,
      reviewCount,
      bestRating: 5,
      worstRating: 1,
    },
    reviews,
    lastUpdated: new Date().toISOString(),
    autoGenerated: true,
  };
}

// Otomatik yorumlar oluştur
export function generateAutoReviews(region: any, count?: number): any[] {
  const reviewTemplates = [
    {
      rating: 5,
      text: `${region.sourceCity}'dan ${region.targetCity}'e taşınma işlemimiz sorunsuz geçti. Profesyonel ekip, güler yüzlü hizmet. Teşekkürler!`,
    },
    {
      rating: 5,
      text: `Çok memnun kaldık. Eşyalarımız hiç zarar görmeden ${region.targetCity}'e ulaştı. Kesinlikle tavsiye ederim.`,
    },
    {
      rating: 4,
      text: `Genel olarak memnun kaldık. ${region.sourceCity} ${region.targetCity} arası sorunsuz taşındık.`,
    },
    {
      rating: 5,
      text: `Fiyat/performans açısından çok iyi. ${region.sourceCity} ${region.targetCity} arası nakliyat için ideal firma.`,
    },
    {
      rating: 5,
      text: `Profesyonel hizmet, uygun fiyat. ${region.sourceCity}'dan ${region.targetCity}'e taşınmak için harika bir seçim.`,
    },
    {
      rating: 4,
      text: `İyi bir deneyimdi. Eşyalarımız güvenle ${region.targetCity}'e ulaştı.`,
    },
  ];

  const reviewCount = count || Math.floor(Math.random() * 6) + 5; // 5-10 arası
  const reviews = [];

  for (let i = 0; i < reviewCount; i++) {
    const template = reviewTemplates[Math.floor(Math.random() * reviewTemplates.length)];
    reviews.push({
      id: `review-${Date.now()}-${i}`,
      author: generateRandomName(),
      rating: template.rating,
      date: generateRandomDate(),
      text: template.text,
      verified: Math.random() > 0.3,
    });
  }

  return reviews;
}

// Rastgele Türk ismi oluştur
function generateRandomName(): string {
  const firstNames = ['Ahmet', 'Mehmet', 'Ayşe', 'Fatma', 'Ali', 'Zeynep', 'Mustafa', 'Elif', 'Hasan', 'Merve'];
  const lastNames = ['Y.', 'K.', 'D.', 'Ç.', 'Ş.', 'Ö.', 'A.', 'T.', 'E.', 'B.'];
  
  const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
  const lastInitial = lastNames[Math.floor(Math.random() * lastNames.length)];
  
  return `${firstName} ${lastInitial}`;
}

// Rastgele tarih (son 6 ay içinde)
function generateRandomDate(): string {
  const now = new Date();
  const sixMonthsAgo = new Date(now.getTime() - 180 * 24 * 60 * 60 * 1000);
  const randomTime = sixMonthsAgo.getTime() + Math.random() * (now.getTime() - sixMonthsAgo.getTime());
  return new Date(randomTime).toISOString().split('T')[0];
}

export function calculateAggregateRating(reviews: any[]) {
  if (reviews.length === 0) {
    return {
      ratingValue: 4.7,
      reviewCount: 15,
      bestRating: 5,
      worstRating: 1,
    };
  }
  
  const totalRating = reviews.reduce((sum, review) => sum + review.rating, 0);
  const avgRating = totalRating / reviews.length;
  
  return {
    ratingValue: Math.round(avgRating * 10) / 10,
    reviewCount: reviews.length,
    bestRating: 5,
    worstRating: 1,
  };
}
