import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/auth/session';
import fs from 'fs/promises';
import path from 'path';
import { generateRegionRating } from '@/lib/ratings/auto-generate';

const RATINGS_DIR = path.join(process.cwd(), 'data/ratings');

// GET - Bölge rating'ini getir
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  
  try {
    const filePath = path.join(RATINGS_DIR, `${id}-rating.json`);
    
    try {
      const data = await fs.readFile(filePath, 'utf-8');
      return NextResponse.json(JSON.parse(data));
    } catch (error) {
      // Rating yoksa otomatik oluştur
      const regionPath = path.join(process.cwd(), 'data/regions', `${id}.json`);
      const regionData = await fs.readFile(regionPath, 'utf-8');
      const region = JSON.parse(regionData);
      
      const newRating = generateRegionRating(region);
      await fs.writeFile(filePath, JSON.stringify(newRating, null, 2), 'utf-8');
      
      return NextResponse.json(newRating);
    }
  } catch (error) {
    return NextResponse.json({ error: 'Rating bulunamadı' }, { status: 404 });
  }
}

// PUT - Rating güncelle
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const session = await getSession();
  
  if (!session) {
    return NextResponse.json({ error: 'Yetkisiz erişim' }, { status: 401 });
  }

  try {
    const body = await request.json();
    const rating = {
      ...body,
      regionId: id,
      lastUpdated: new Date().toISOString(),
      autoGenerated: false,
    };
    
    const filePath = path.join(RATINGS_DIR, `${id}-rating.json`);
    await fs.writeFile(filePath, JSON.stringify(rating, null, 2), 'utf-8');
    
    return NextResponse.json({ success: true, data: rating });
  } catch (error) {
    return NextResponse.json({ error: 'Rating güncellenemedi' }, { status: 500 });
  }
}

// POST - Otomatik rating oluştur
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const session = await getSession();
  
  if (!session) {
    return NextResponse.json({ error: 'Yetkisiz erişim' }, { status: 401 });
  }

  try {
    const regionPath = path.join(process.cwd(), 'data/regions', `${id}.json`);
    const regionData = await fs.readFile(regionPath, 'utf-8');
    const region = JSON.parse(regionData);
    
    const newRating = generateRegionRating(region);
    
    const filePath = path.join(RATINGS_DIR, `${id}-rating.json`);
    await fs.writeFile(filePath, JSON.stringify(newRating, null, 2), 'utf-8');
    
    return NextResponse.json({ success: true, data: newRating });
  } catch (error) {
    return NextResponse.json({ error: 'Rating oluşturulamadı' }, { status: 500 });
  }
}
